-- MySQL Script generated by MySQL Workbench
-- Fri Feb  9 15:59:17 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `new_schema1` ;
USE `new_schema1` ;

-- -----------------------------------------------------
-- Table `new_schema1`.`movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`movies` (
  `title` VARCHAR(45) NOT NULL,
  `actors` VARCHAR(45) NULL,
  `director` VARCHAR(45) NULL,
  `producer` VARCHAR(45) NULL,
  `year_of_prod` YEAR NULL,
  `language` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL,
  `storyline` TEXT(120) NULL,
  `video` VARCHAR(45) NULL,
  PRIMARY KEY (`title`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
